SOLVER:
  BATCH_SIZE: 16
  MAX_EPOCH: 120
  LR: 1e-4
  SSL_LR: 3e-5
  CM_LR: 1e-5
  SEED: 42
  NUM_WORKERS: 4

RS:
  SSL: True
  CM: True
  INIT_EPOCH: 6
  EPOCH_STEP: 6
  MAX_MARGIN: 0.5
  RESET_EPOCH: 120

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "DrugLAMP"
  TAG: ""