SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 100
  LR: 5e-5
  SSL_LR: 5e-5
  CM_LR: 5e-5
  SEED: 42
  NUM_WORKERS: 8

RS:
  SSL: False
  CM: False
  INIT_EPOCH: 5
  EPOCH_STEP: 5
  MAX_MARGIN: 0.5
  RESET_EPOCH: 100

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "DrugLAMP"
  TAG: "Reproduce-bsz_32-DrugLAMPwoSSL"